public enum PoolableTypeEnum
{
    STANDARD,
    AGENT_CREATURE,
    AGENT_STRUCTURE,
    UI_SLIDER,
    UI_FLOATTEXT,
    ATTACK_RANGED,
    ATTACK_MELEE,
    ATTACK_IMMEDIATE,
    ATTACK_OUTCOME,
    STATUS_AFFECTOR_FREEZE,
    STATUS_AFFECTOR_BURN,
    STATUS_AFFECTOR_PARALYZE,
    STATUS_AFFECTOR_DROWN,
    STATUS_AFFECTOR_CONFUSION,
    STATUS_AFFECTOR_POISON,
    STATUS_AFFECTOR_ASLEEP,
    STATUS_AFFECTOR_GROUNDED,
    STATUS_AFFECTOR_HEALBLOCK,
    STATUS_AFFECTOR_TAUNT,
    AFX_ATTACKING,
    AFX_MISCELANOUS,
    SFX_CREATURES,
    SFX_STRUCTURES,
    SFX_MISCELANOUS,
    UI_BUTTON,
    UI_HORIZONTALLAYOUT,
}

////////////////////////////////////////////////////////////////////////////////
////////////SCRIPT MADE BY JAISON ROBSON GUSAVA UNDER MIT LICENSE///////////////
/////////////////////// https://github.com/jaisonrobson/ ///////////////////////